eureka:
  client:
    fetch-registry: false
    # 不注册自己
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.host}:${eureka.port}/eureka/
  # 注册中心地址
  host: localhost
  port: 1111

server:
  port: 1111

spring:
  application:
    name: sop-registry