FROM java:8
VOLUME /tmp
VOLUME /log
ADD *.jar app.jar

ENV JAVA_OPTS="-Xms128m -Xmx128m"
# springboot配置文件
ENV CONF=" --logging.file=log/spring.log --mysql.host=10.1.30.120:3306 --register.url=10.1.30.110:8848"

ENTRYPOINT java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /app.jar ${CONF}