FROM java:8
VOLUME /tmp
VOLUME /log
ADD *.jar app.jar

# JVM设置
ENV JAVA_OPTS="-Xms128m -Xmx128m"

# springboot配置文件
#  --logging.file：日志
#  --mysql.host：mysql地址
#  --register.url：nacos地址
ENV CONF="--logging.file=log/spring.log --mysql.host=10.1.30.120:3306 --register.url=10.1.30.110:8848"

ENTRYPOINT java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar /app.jar ${CONF}