server:
  port: 8082

# token过期时间，分钟
admin:
  access-token:
    timeout-minutes: 30

# 不用改
spring:
  application:
    name: sop-admin

  # zookeeper客户端连接
  cloud:
    zookeeper:
      connect-string: localhost:2181
      baseSleepTimeMs: 3000
      maxRetries: 3

  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sop?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root


# 固定不用改
easyopen:
  show-doc: true
  mono: false
  ignore-validate: true

# 注册中心地址，根据实际情况改，这里只是参数，并不会去注册
eureka:
  port: 1111
  host: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.host}:${eureka.port}/eureka/

# 根据实际情况改
logging:
  level:
    com:
      gitee: debug

# 不用改
mybatis:
  fill: {com.gitee.fastmybatis.core.support.DateFillInsert: gmt_create,
         com.gitee.fastmybatis.core.support.DateFillUpdate: gmt_modified}
