server:
  port: 2222

spring:
  application:
    name: story-service
    description: story服务

  cloud:
    zookeeper:
      connect-string: localhost:2181

    # nacos注册中心，和eureka只能用一个
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848

# eureka注册中心，如果使用nacos注册中心，这里要注释掉
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# dubbo provider
dubbo:
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: N/A
  scan:
    base-packages: com.gitee.sop.storyweb.service
