server:
  port: 2222

spring:
  application:
    name: story-service
    description: story服务

  cloud:
    zookeeper:
      connect-string: localhost:2181

# 注册中心
eureka:
  port: 1111
  host: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.host}:${eureka.port}/eureka/

# dubbo provider
dubbo:
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: N/A
  scan:
    base-packages: com.gitee.sop.storyweb.service
