server:
  port: 3333

spring:
  application:
    name: book-service

  cloud:
    zookeeper:
      # zookeeper配置
      connect-string: localhost:2181

    # nacos注册中心，和eureka只能用一个
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# eureka注册中心，如果使用nacos注册中心，这里要注释掉
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:1111/eureka/

# dubbo consumer
demo:
  service:
    version: 1.0.0
dubbo:
  application:
    id: dubbo-consumer-demo
    name: dubbo-consumer-demo
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
management:
  port: 8081