server:
  port: 3333

spring:
  application:
    name: book-service

  cloud:
    zookeeper:
      # zookeeper配置
      connect-string: localhost:2181

eureka:
  port: 1111
  host: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.host}:${eureka.port}/eureka/