server:
  port: 3333

spring:
  application:
    name: book-service

  cloud:
    zookeeper:
      # zookeeper配置
      connect-string: localhost:2181

eureka:
  port: 1111
  host: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.host}:${eureka.port}/eureka/

# dubbo consumer
demo:
  service:
    version: 1.0.0
dubbo:
  application:
    id: dubbo-consumer-demo
    name: dubbo-consumer-demo
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
management:
  port: 8081