server:
  port: 8081

zuul:
  # 入口地址，不用改，默认是/zuul
  servlet-path: /api

# 注册中心
eureka:
  serverAddr: localhost:1111
  client:
    serviceUrl:
      defaultZone: http://${eureka.serverAddr}/eureka/

spring:
  application:
    name: api-gateway

  cloud:
    zookeeper:
      connect-string: 10.1.31.126:2181

    gateway: # Spring Cloud Gateway配置，如果用了zuul，这段配置没有效果
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true


  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sop?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root