server:
  port: 8081


eureka:
  serverAddr: localhost:1111
  client:
    serviceUrl:
      defaultZone: http://${eureka.serverAddr}/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

