server:
  port: 8081

# 注册中心
eureka:
  serverAddr: localhost:1111
  client:
    serviceUrl:
      defaultZone: http://${eureka.serverAddr}/eureka/

spring:
  cloud:
    gateway: # Spring Cloud Gateway配置，如果用了zuul，这段配置没有效果
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sop?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root