server:
  port: 8081


eureka:
  serverAddr: localhost:1111
  client:
    serviceUrl:
      defaultZone: http://${eureka.serverAddr}/eureka/

spring:
  cloud:
    gateway: # Spring Cloud Gateway配置，如果用了zuul，这段配置没有效果
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

