server:
  port: 8083

# 注册中心
eureka:
  serverAddr: localhost:1111
  client:
    serviceUrl:
      defaultZone: http://${eureka.serverAddr}/eureka/

spring:
  application:
    name: website-server

  cloud:
    zookeeper:
      connect-string: localhost:2181

api:
  # 测试地址
  url-test: http://api-test.yourdomain.com/api
  # 沙箱环境
  url-sandbox: http://localhost:8081/api
  # 正式地址
  url-prod: http://open.yourdomain.com/api
  pwd: doc#123