server:
  port: 8083

# 注册中心地址，根据实际情况改，这里只是参数，并不会去注册
registry:
  eureka-server-addr: http://localhost:1111/eureka/
  # nacos服务器地址
  nacos-server-addr: 127.0.0.1:8848
  # 使用eureka，填：eureka，使用nacos填：nacos
  name: nacos

spring:
  application:
    name: website-server

  cloud:
    zookeeper:
      connect-string: localhost:2181

api:
  # 测试地址
  url-test: http://api-test.yourdomain.com/api
  # 沙箱环境
  url-sandbox: http://localhost:8081/api
  # 正式地址
  url-prod: http://open.yourdomain.com/api
  pwd: doc#123